apiVersion: v2
name: calcengine
description: Helm chart for calcengine (java-ajsc)
type: application
version: 1.0.0
appVersion: 1.0.0
maintainers:
- name: Platform Engineering
  email: platform-eng@company.com
keywords:
- java-ajsc
- aks
- microservice
