namespace: com-att-attcc-preprod
replicaCount: 2
resources:
  requests:
    memory: 9Gi
    cpu: '2'
  limits:
    memory: 10Gi
    cpu: '4'
javaOpts: -Xms512m -Xmx2048m -XX:MetaspaceSize=512m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode
  -Dhttp.nonProxyHosts=*.windows.net -Dhttps.nonProxyHosts=*.windows.net -Djavax.xml.parsers.SAXParserFactory=org.apache.xerces.jaxp.SAXParserFactoryImpl
envOverrides:
- name: ROUTEOFFER
  value: D2A
- name: ENVCONTEXT
  value: TEST
- name: AFTENVIRONMENT
  value: AFTUAT
- name: AFTLATITUDE
  value: '35.4'
- name: AFTLONGITUDE
  value: '-81.5'
- name: CSI_CLUSTER
  value: D6A
- name: WMQ_ENVCONTEXT
  value: D
- name: GL_ENV
  value: DEVL,V_DEVL
- name: DEBUG_LEVEL
  value: INFO
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodepool
          operator: In
          values:
          - ruleengine
