apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configFiles }}
  {{ $key }}: |
    {{ $value | nindent 4 }}
  {{- end }}
