{{- $root := . -}}
{{- $services := .Values.services | default (list (dict)) -}}
{{- range $idx, $s := $services }}
{{- if $idx }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" $root }}{{ with $s.suffix }}-{{ . }}{{ end }}
  namespace: {{ $root.Values.namespace | default $root.Release.Namespace }}
  labels:
    app: {{ if $s.suffix }}{{ printf "%s-%s" ($root.Values.appLabel | default (include "name" $root)) $s.suffix }}{{ else }}{{ $root.Values.appLabel | default (include "name" $root) }}{{ end }}
    version: {{ $root.Values.image.tag | default $root.Chart.AppVersion | quote }}
spec:
  type: {{ $root.Values.service.type }}
  ports:
    - port: {{ $root.Values.service.port }}
      targetPort: {{ $root.Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ if $s.suffix }}{{ printf "%s-%s" ($root.Values.appLabel | default (include "name" $root)) $s.suffix }}{{ else }}{{ $root.Values.appLabel | default (include "name" $root) }}{{ end }}
{{- end }}
