basic_realm={{cadi_basic_realm}}
basic_warn={{cadi_basic_warn}}
 
cadi_loglevel={{cadi_loglevel}}

cadi_keyfile={{cadi_keyfile_path}}


 
cadi_protocols={{cadi_protocols}}

aaf_env={{aaf_env_var}}

#aaf_url=https://DME2RESOLVE/service=com.att.authz.AuthorizationService/version=2.0/envContext=TEST/routeOffer=BAU_SE
#AFT_LATITUDE={{AFTLATITUDE}}
#AFT_LONGITUDE={{AFTLONGITUDE}}
#AFT_ENVIRONMENT={{AFTENVIRONMENT}}

aaf_url={{cadi_aaf_url}}
aaf_locate_url={{cadi_aaf_locate_url}}
aaf_lur={{cadi_aaf_lur}}
 
#Commenting these 2 lines until CADI fixes Authorization issue in 1.4.2 cadi jars - CPFSDKJAVA-1830
#aaf_oauth2_token_url={{cadi_aaf_oauth2_token_url}}
#aaf_oauth2_introspect_url={{cadi_aaf_oauth2_introspect_url}}

aaf_id={{ cadi_aaf_id }}
aaf_password={{ cadi_aaf_password }}

aaf_timeout={{cadi_aaf_timeout}}

cadi_latitude={{AFT_LATITUDE}}
cadi_longitude={{AFT_LONGITUDE}}