java.naming.factory.initial={{ java_naming_factory_initial }}
java.naming.provider.url={{ java_naming_provider_url }}
jms.queue.connection.factory={{ jms_queue_connection_factory }}
jms.session.max={{ jms_session_max }}
jms.delivery.mode={{ jms_delivery_mode }}
jms.timeout={{ jms_timeout }}
jms.priority={{ jms_priority }}
JMS.user=
JMS.password=