apiVersion: v1
data:
  oidc_client_id: {{ANS_client_id}}
  oidc_client_secret: {{ANS_client_secret}}
kind: Secret
metadata:
  name: {{ANS_msname}}-{{version_major_minor}}-{{ROUTEOFFER|lower}}-oidc-secret
  namespace: {{ANS_NAMESPACE}}
  labels:
    app: {{ANS_app_name}}
    version: "{{ANS_VERSION}}"
    routeoffer: {{ROUTEOFFER}}
type: Opaque