com.att.aft.discovery.client.environment={{com_att_aft_discovery_client_environment}}
com.att.aft.discovery.client.latitude={{com_att_aft_discovery_client_latitude}}
com.att.aft.discovery.client.longitude={{com_att_aft_discovery_client_longitude}}
com.att.aft.keyStore={{com_att_aft_keyStore}}
com.att.aft.keyStorePassword={{com_att_aft_keyStorePassword}}
com.att.aft.trustStore={{com_att_aft_trustStore}}
com.att.aft.trustStorePassword={{com_att_aft_trustStorePassword}}
com.att.aft.alias={{com_att_aft_alias}}