info.build.artifact=@project.artifactId@
info.build.name=@project.name@
info.build.description=@project.description@
info.build.version=@project.version@
info.build.groupId=@project.groupId@
logging.level.root={{ logging_level_root }}

logging.level.org.mongodb=off

eco.seed.name=ajsc7_jersey
eco.seed.version=7.14.1-RELEASE
eco.seed.created.datetime=Tue May 17 16:30:06 UTC 2022

server.servlet.contextPath=/
server.servlet-path=/
spring.jersey.application-path=/calcengine/v1
server.routingPath=/
mots.application.acronym={{mots_application_acronym}}
platform.identifier=AJSC7_JERSEY
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr($ threadId: {PID:- }){magenta} %clr(---){faint} %clr([ hostname: %X{hostname} serviceName: %X{serviceName} version: %X{version} transactionId: %X{transactionId} requestTimeStamp: %X{requestTimestamp}  responseTimeStamp: %X{responseTimestamp} duration: %X{duration}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex

#The max number of active threads in this pool
server.tomcat.max-threads={{ server_tomcat_max_threads }}
#The minimum number of threads always kept alive
server.tomcat.min-Spare-Threads={{ server_tomcat_min_Spare_Threads }}
#The number of milliseconds before an idle thread shutsdown, unless the number of active threads are less or equal to minSpareThreads
server.tomcat.max-idle-time={{ server_tomcat_max_idle_time }}

#for changing the tomcat port...
#server.port=8081

#Management server port for accessing actuator endpoints...
management.server.port={{server_health_port}}

# Expose endpoints to web...
management.endpoints.web.exposure.include=info,health,prometheus

# Turn off all endpoints by default and enable only info, health and Prometheus only...
management.endpoints.enabled-by-default=false
management.endpoint.info.enabled=true
management.endpoint.health.enabled=true
management.endpoint.prometheus.enabled=true

#Servlet context parameters
server.context_parameters.p-name={{ server_context_parameters_p_name }} #context parameter with p-name as key and value as value.

#Service System Properties. Please, place any Service related System Properties below.
#masterEndPointOverrideMap.location=etc/MasterEndPointOverrideMap.xml
#adapterDME2UrlMap.location=etc/AdapterDME2UrlMap.xml
#AdapterMap.location=etc/Adapter.map
#defaultDME2EnvContext=TEST
#com.att.aft.dme2.jms.stickySelectorKey=

#path for application environment file 
#env.path=etc/env-application.properties
#aaf.roles.properties=etc-local/AAFUserRoles.properties 
#cadi.properties.location=etc-local/cadi.properties

# make this true for AAF authentication and place cadi.properties into etc folder
#aaf.enabled=false

# set to true to enable version proxy
#ivp.enabled=false

